server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth-service/**
          filters:
            - StripPrefix=1
        - id: project-service
          uri: lb://PROJECT-SERVICE
          predicates:
            - Path=/project-service/**
          filters:
            - StripPrefix=1
        - id: resource-service
          uri: lb://RESOURCE-SERVICE
          predicates:
            - Path=/resource-service/**
          filters:
            - StripPrefix=1
        - id: collab-service
          uri: lb://COLLAB-SERVICE
          predicates:
            - Path=/collab-service/**
          filters:
            - StripPrefix=1
        - id: lambda-report-service
          uri: https://ehhwnfz5czyrav25erh36mpnlq0cvglk.lambda-url.us-east-1.on.aws
          predicates:
            - Path=/reports/**
          filters:
            - StripPrefix=1
            - RemoveRequestHeader=Host

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.server: DEBUG
