server:
  port: 9004
spring:
  application:
    name: collab-service
jwt:
  secret: very-long-secret-key-for-jwt-signing-123456
  expiration-ms: 3600000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
